language: java
script:
  - ./gradlew check
cache:
  directories:
  - $HOME/.gradle
jdk:
  - oraclejdk8
  - openjdk6
env:
  global:
  - TERM=dumb
  - DEFAULT_TIMEOUT_MILLIS=300
  - PUBLISHER_REFERENCE_GC_TIMEOUT_MILLIS=300
addons:
  # Fix OpenJDK build. Issue: https://github.com/travis-ci/travis-ci/issues/5227 & https://docs.travis-ci.com/user/hostname
  hostname: short-hostname
